### ISSUE TITLE
the script is still trying to do something when i press  CTRL +C

### ISSUE THREAD

**Issue by stunner999** [Wraient/curd#1]
I expected it to stop but it searching something instead. I hope you can understand what I mean

**Comment by Wraient** [comment]
Yes, i know exactly what you mean, and i've been working on that problem. I would commit a fix soon.

**Comment by Wraient** [comment]
till then you can try doing the ctrl + c a few times

**Comment by Wraient** [comment]
[91e1ba3](https://github.com/Wraient/curd/commit/91e1ba304abf73ccb8843f169bf08d187d152eaf)

I know its not completely fixed, i am planning to rewrite this program in go, maybe it'll be fixed in the rewrite.

**Comment by ttx99** [comment]
@Wraient fixed thx
