### ISSUE TITLE
Runtime Error opening curd on Windows 8.1

### ISSUE THREAD

**Issue by Likver** [Wraient/curd#11]
When opening curd from the shortcut it makes in the desktop after installing, or opening it from the installed folder, it shows a panic runtime error

**To Reproduce**
Open the shortcut or exe on win8.1

**Screenshots**
![image](https://github.com/user-attachments/assets/819e9fae-b888-4d94-a275-8af752508509)

**Environment (please complete the following information):**
 - Windows 8.1

**Debug logs**
Theres no log file or i couldnt find one in ``C:\Users\$USER$\AppData\Local``

Its probably that the program isnt compatible with win8.1, if its not, is there any plans or motivation to make it compatible with 8.1?

**Comment by Wraient** [comment]
The latest windows curd installer is not stable please use the installer from [v0.0.3](https://github.com/Wraient/curd/releases/tag/v0.0.3) after deleting the installed folder 
I'll fix this issue when I get home, if this does not work, ping me

**Comment by Likver** [comment]
v0.0.3 installer worked, but after pasting the token i think it didnt paste fully (for whatever reason) and even after reinstalling (removing also the folder in ``C:\Users\$USER$\.config\curd``) it keeps saying  ``Failed to get user ID, Press Enter or ESC to exit``
is there another file im missing that has to be removed to be able to re-do the token step?

**Comment by Wraient** [comment]
yes the token is stored in C:\.local\share\curd\token for windows (there is a dot before "local")
Ill add an option to change the token.

**Comment by Wraient** [comment]
[748f9a9](https://github.com/Wraient/curd/commit/748f9a98852cafb4db0204f6a537a6f5401d92c5) You can now change the token using "curd -change-token" 
For your case, the "curd -u" would download the latest binary but it wont be able to change the name of the binary from "curd.exe.tmp" to "curd.exe" due to lack of adminsitrator priveleges in windows, you can try  doing it from administrator command prompt and it might work, let me know if you have any other problems

**Comment by Wraient** [comment]
You can also manually download the curd.exe binary from latest release, [v0.0.5](https://github.com/Wraient/curd/releases/tag/v0.0.5) it will work for windows now.

**Comment by Likver** [comment]
now i keep getting ``Error selecting anime`` when doing ``curd``, even after i updated to latest version just downloading the curd.exe and moving it into the path where it was installed

**Comment by Wraient** [comment]
ah there are just too many bugs for rofi, if you have changed your token, use the v0.0.3 curd.exe I'll test and debug everything in windows today

**Comment by Likver** [comment]
> ah there are just too many bugs for rofi, if you have changed your token, use the v0.0.3 curd.exe I'll test and debug everything in windows today

oh no the thing is i cant do anything at all, doesnt matter if i use 0.0.3 or 0.0.5

**Comment by Wraient** [comment]
what happens in 0.0.3

**Comment by Wraient** [comment]
can you come on discord ? @wraient

**Comment by Likver** [comment]
> what happens in 0.0.3

this is what happens in both 0.0.3 and 0.0.5
![image](https://github.com/user-attachments/assets/06c5fa1d-e57e-4a98-8f23-6929fc102faa)


> can you come on discord ? @Wraient

yeah sure, my username lik__

**Comment by Wraient** [comment]
I've send you a request and my discord is 
wraient

**Comment by Wraient** [comment]
Apparently Console modes are not compatiable with Windows 8.1.
Curd is not supported for windows 8.1
:(
