### ISSUE TITLE
Use without anilist token

### ISSUE THREAD

**Issue by ykhan21** [Wraient/curd#15]
Is it possible to use this without an anilist token?

**Comment by Wraient** [comment]
No, without anilist integration you would not be able to use most of the features of this program such as
1. Image preview of anime
2. Skip Filler times
3. The anime poster in Discord rpc
4. Update anilist progress
5. The whole progress tracking of anime is ground up build on the fact that you are storing your real progress in anilist, so this would not work.


You are better off using [ani-cli](https://github.com/pystardust/ani-cli) if you dont want all these features.


I might add this feature later with some work around, but currently you need an anilist token to use this application
