### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by ttx99** [Wraient/curd#16]
Search (Press Ctrl+C to quit):
Filter:
▶ Dragon Ball DAIMA
  One Punch Man 3
  Add new anime
  Quit
Failed to automatically select anime
Search (Press Ctrl+C to quit):
Filter:
  Dragon Ball Daima (4 episodes)
▶ Quit
Failed to get anime data. Attempting to retrieve from anime list.
Still unable to determine total episodes.
Your AniList progress: 4
Enter the episode you want to start from:

### _I mean I really wanna quit._

**Comment by Wraient** [comment]
[07c1ff](https://github.com/Wraient/curd/commit/07c1ff74dbd1f9893d0ec70fc4ae1f6ebe329252)
```
sudo curd -u
```
and it should work.

p.s. why're you using the terminal menu? rofi looks much better
