### ISSUE TITLE
where to paste this?

### ISSUE THREAD

**Issue by ttx99** [Wraient/curd#17]
![1](https://github.com/user-attachments/assets/429cd75d-cecd-4a73-880a-2e9cdcf2d00e)

**Comment by ttx99** [comment]
![1](https://github.com/user-attachments/assets/6e11c804-487c-4082-b128-aedd343ed3a3)

**Comment by Wraient** [comment]
the application isn't working because anilist API is down right now.

**Comment by Wraient** [comment]
API for applications has been enabled by anilist, curd works now. Tell me if you can use it and ill close this issue

**Comment by ttx99** [comment]
Im still stuck with this
![1](https://github.com/user-attachments/assets/63c6c04b-0c13-45de-9020-3f9e646da255)

**Comment by Wraient** [comment]
oh well you need a new token do
`curd -change-token`
and it'll prompt you to change your token

**Comment by Wraient** [comment]
okay anilist is down again.. I don't know when it will be fixed, the site is coming up and going down every few hours since a week. please look in the anilist discord server for more info

**Comment by ttx99** [comment]
thx its okay now
