### ISSUE TITLE
error update AUR

### ISSUE THREAD

**Issue by ttx99** [Wraient/curd#3]
![1](https://github.com/user-attachments/assets/2f06dcc0-f27b-4fa6-9ac5-223328850c4a)

**Comment by Wraient** [comment]
I cannot recreate this error, you can try 
```
paru -Rns curd
paru -Scc
```
which would remove curd and all the cache file (your history and config are saved.)
and then try reinstalling it
```
paru -Sy curd
```
if it still does not work, try installing it manually with 
```
curl -Lo curd https://github.com/Wraient/curd/releases/latest/download/curd
chmod +x curd
sudo mv curd /usr/bin/curd
```

Ping me if you have any problems

**Comment by ttx99** [comment]
Did the manual install thx
![1](https://github.com/user-attachments/assets/93ce4e61-eab6-4088-9ad2-d3bebc70b301)
